### ISSUE TITLE
Vayne/OKTW Failed?

### ISSUE THREAD

**Issue by crazycloak** [berbb/PortAIO-Standalone#5]
I can't successfully install those 2....

**Comment by berbb** [comment]
You need to install sebby lib

**Comment by crazycloak** [comment]
I have it already....

**Comment by crazycloak** [comment]
VayneHunter still can't be installed, but OKTW seems fine now.

**Comment by berbb** [comment]
You also need DZlib for vhr

**Comment by crazycloak** [comment]
Yes, i had already installed all the libs before and as today still unable to download it.
